apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems-app
  template:
    metadata:
      labels:
        app: ems-app
    spec:
      containers:
        - name: ems-backend
          image: ajith151020/ems-backend:jenkins-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ems-service
spec:
  type: NodePort
  selector:
    app: ems-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001